support integers
JaneliaSciComp/BatchedBLAS.jl pull request #3
Opened 2022-03-23 19:14 UTC by bjarthur

for example:

```
using CUDA, BatchedBLAS
L=32; N=4096;
A=CuArray(rand(Int16, L, L, N));   # any or all of the input types can now be <:Integer
x=CuArray(rand(Float32, L, N));
y=CuArray(rand(Float32, L, N));
batched_gemv!('N', 0.5, A, x, 0.0, y);
```

2022-03-23 22:03 UTC, mkitti requested changes
I think we can come up with a better design than using `float2int` everywhere by using a custom boxed type.

2022-03-23 22:03 UTC, mkitti commented on src/BatchedBLAS.jl
> +end
Rather than doing this perhaps we create a custom boxed type that we can override type promotion and conversion for. To get back the original type, we then just use `reinterpret`.

2022-03-24 12:35 UTC, bjarthur commented on test/runtests.jl
> +    end
thanks.  i guess i wasn't concerned about making the tests performant.  probably easiest to prepend an `@views` to the for-block.

2022-03-24 12:57 UTC, bjarthur commented on src/BatchedBLAS.jl
> +end
if the output type is integer, and any of the inputs are float, then we need to clamp and round the accumulated result.  `clamp(x::AbstractFloat, ::Type{Integer})` [does not exist](https://github.com/JuliaLang/julia/issues/40469) in Base.  this was my hack at it just for proof of concept to work out this package's API and functionality.  need to decide now whether it's worth spending the time to make a PR to Base.  will probably start with [these additions](https://github.com/JaneliaSciComp/BatchedBLAS.jl/pull/3/files#diff-3b9314a6f9f2d7eec1d0ef69fa76cfabafdbe6d0df923768f9ec32f27a249c63R14-R16) to Base first.

2022-04-05 20:33 UTC, merged